mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^polls/', include('polls.urls', namespace='polls')),
]

mysite/polls/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='details'),
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
]

mysite/polls/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.

@python_2_unicode_compatible
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	
	def __str__(self):
		return self.question_text
		
	def was_published_recently(self):
		# this method returns true of the question was published in the last 24 hours
		
		return True

@python_2_unicode_compatible
class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	
	def __str__(self):
		return self.choice_text

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse

from django.views import generic

from . models import Question, Choice

# Create your views here.

class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'
	
	def get_queryset(self):
		return Question.objects.order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/details.html'

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		context = {
			'question': question,
			'error_message': "You didn't pick anything",
		}
		return render(request, 'polls/details.html', context)
	else:
		selected_choice.votes += 1
		selected_choice.save()
		return HttpResponseRedirect(reverse('polls:results', args=(question.id, )))

class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'

mysite/polls/templates/polls/details.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}
	<p><strong>{{ error_message }}</strong></p>
{% endif %}
<form method="POST" action="{% url 'polls:vote' question.id %}">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
		<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}"/>
		<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label>
		<br/>
	{% endfor %}
	<input type="submit" value="Vote!"/>
</form>

mysite/polls/templates/polls/index.html
{% load static %}
<html>
<head>
	<link href="{% static 'polls/style.css' %}" rel="stylesheet"/>
	<title>My amazing poll site!</title>
</head>

<body>

	{% if latest_question_list %}
	<ul>
		{% for question in latest_question_list %}
			<li>
				<a href="/polls/{{ question.id }}/" >{{ question.question_text }}</a>
			</li>
		{% endfor %}
	</ul>
	{% else %}
		<p>No polls are available</p>
	{% endif %}
</body>
</html>

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
	{% for choice in question.choice_set.all %}
		<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
	
	{% endfor %}
</ul>

<a href="{% url 'polls:details' question.id %}" >Vote again?</a>